import type { ProviderProps } from '@ant-design/react-native';

import { components, palette, radii, spacing, typography } from '@/theme';

export const antdTheme = {
  brand_primary: palette.primary,
  brand_primary_tap: palette.primaryDark,
  brand_success: palette.success,
  brand_warning: palette.warning,
  brand_error: palette.error,
  color_link: palette.primary,
  color_text_base: palette.ink,
  color_text_caption: palette.muted,
  color_text_placeholder: palette.placeholder,
  color_text_paragraph: palette.text,
  fill_body: palette.canvas,
  fill_base: palette.surface,
  fill_grey: palette.paper,
  fill_tap: palette.primarySoft,
  border_color_base: palette.borderStrong,
  border_color_thin: palette.border,
  button_height: components.buttonPrimaryHeight,
  button_font_size: 15,
  primary_button_fill: palette.primary,
  primary_button_fill_tap: palette.primaryDark,
  ghost_button_color: palette.ink,
  ghost_button_fill_tap: palette.graySoft,
  radius_sm: radii.sm,
  radius_md: radii.md,
  radius_lg: radii.lg,
  font_size_base: typography.body,
  font_size_caption: typography.caption,
  font_size_heading: typography.h2,
  h_spacing_sm: spacing.sm,
  h_spacing_md: spacing.md,
  h_spacing_lg: spacing.lg,
  v_spacing_sm: spacing.sm,
  v_spacing_md: spacing.md,
  v_spacing_lg: spacing.lg,
} satisfies NonNullable<ProviderProps['theme']>;
