-- Localize blind-box activity cover images under apps/api/assets.
-- Generated by apps/api/scripts/localizeBlindBoxCoverImages.ts.

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 9
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Forbidden_City_Beijing_Shenwumen_Gate.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0010-e7bd25b157.jpg'
WHERE id = 10
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/06/%E9%A2%90%E5%92%8C%E5%9B%AD%E4%B8%87%E5%AF%BF%E5%B1%B1%E4%BD%9B%E9%A6%99%E9%98%81.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0011-8501210579.jpg'
WHERE id = 11
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/93/Jingshan_Park_from_north_gate_of_Forbidden_City.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0012-79c737b5e6.jpg'
WHERE id = 12
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/5/5b/%E5%A5%A5%E6%9E%97%E5%8C%B9%E5%85%8B%E6%A3%AE%E6%9E%97%E5%85%AC%E5%9B%AD%E5%85%A8%E6%99%AF.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0013-798.jpg'
WHERE id = 13
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Space-gallery%20798-art-district.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0014-fb007ce995.jpg'
WHERE id = 14
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://r1.visitbeijing.com.cn/vbj-s/2017/0419/20170419053817825.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0015-a922615db6.jpg'
WHERE id = 15
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Beijing_hutong_Wudaoying_3.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0016-105491467c.jpg'
WHERE id = 16
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/95/Shishahai.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0017-702da33609.jpg'
WHERE id = 17
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://r1.visitbeijing.com.cn/vbj-s/2023/1212/9967be3b17a2112fe03d7030bb041b29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0018-907b171116.jpg'
WHERE id = 18
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/9c/National_Art_Museum_of_China_%2820240627%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0019-d911f60fa9.jpg'
WHERE id = 19
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Shougang_International_Convention_and_Exhibition_Center_during_CIFTIS_2024_%2820240916125402%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0021-c53e6f4b38.jpg'
WHERE id = 21
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/1/12/Muji_Hotel_Beijing_%2820201211133431%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0022-0597318b86.jpg'
WHERE id = 22
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/e/ee/%E4%B8%89%E9%87%8C%E5%B1%AF%E5%A4%AA%E5%8F%A4%E9%87%8C%E5%8D%97%E5%8C%BA.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 24
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://www.meet-in-shanghai.net/cn/uploads/2025/06/12/1933038428293681154.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0025-d7716afbdb.jpg'
WHERE id = 25
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://www.meet-in-shanghai.net/cn/uploads/2025/06/12/1933038428293681154.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0026-918cd2cecc.jpg'
WHERE id = 26
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://cn.storage.shmedia.tech/adfb12d8f3e14cab87e3a6a1590a298b';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0027-352cfa85fa.jpg'
WHERE id = 27
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Sinan_Mansions_Shanghai.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0028-3a1a2335ee.jpg'
WHERE id = 28
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://obj.shine.cn/files/2024/04/21/123d4e26-8562-4f21-b445-ea2acf8774bf_0.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0029-cb6d5b452e.jpg'
WHERE id = 29
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/b/b8/%E5%8C%97%E5%A4%96%E7%81%98%E6%BF%B1%E6%B1%9F%E7%B6%A0%E5%9C%B0.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0030-m50.jpg'
WHERE id = 30
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/0e/201703_M50_Creative_Park.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0031-45abc6ba58.jpg'
WHERE id = 31
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/1/11/%E5%BE%90%E6%B1%87%E6%BB%A8%E6%B1%9F.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0032-493c58aaf8.jpg'
WHERE id = 32
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Yuyuan_Tourist_Mart_outside.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 46
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_Research_Base_Eingang.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0051-02e15c4423.jpg'
WHERE id = 51
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://www.news.cn/politics/20240424/f4ace8da3c1a451b8c95a8c32981e3c3/20240424b4d4d17714d84a33934150737dfdecd5_33e83d025fb44067967bf4a181bfa258.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0053-17ad1709bb.jpg'
WHERE id = 53
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://images.trvl-media.com/place/6209409/9bca385c-7dfc-4655-b508-9de828bd2880.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0054-4b55c562ad.jpg'
WHERE id = 54
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/a/a8/SHK2.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0055-5450998ebd.jpg'
WHERE id = 55
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Chen_Clan_Ancestral_Hall_2025.06_02.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0056-4831e5f36a.jpg'
WHERE id = 56
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/f/f9/North_gate_of_Liwanhu_Park_20080314.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0057-c74a32fdac.jpg'
WHERE id = 57
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://img.qianggen.net/uploadfile/2023/0508/20230508054617823.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0058-b3de47b813.jpg'
WHERE id = 58
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://www.news.cn/politics/20240116/1b8600703bf04c988cae535e155e5f9b/202401161b8600703bf04c988cae535e155e5f9b_59ca5667b2364d52846a8812b224c1c1.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0059-74f49a6787.jpg'
WHERE id = 59
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Haizhu_Lake.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0062-8076d92dee.jpg'
WHERE id = 62
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://huacheng.gz-cmc.com/upload/news/image/2021/10/05/dde21028711846d480ecbbbe9cf6434d.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0064-c49567a2b5.jpg'
WHERE id = 64
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://p1-mp.oeeee.com/202301/24/2047x3000_63cf5db46bca2.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0065-2f2ab5b481.jpg'
WHERE id = 65
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0066-25cb40a923.jpg'
WHERE id = 66
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Hangzhou_Lingyin-Temple_20161003.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0067-2a1bf861c9.jpg'
WHERE id = 67
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Jiuxiyanshu.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0068-ef30313041.jpg'
WHERE id = 68
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0069-d978f57b19.jpg'
WHERE id = 69
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0070-8b8ac7682e.jpg'
WHERE id = 70
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0071-95ba2c75c2.jpg'
WHERE id = 71
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0073-e418f194cc.jpg'
WHERE id = 73
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E4%B8%AD%E5%9B%BD%E8%8C%B6%E5%8F%B6%E5%8D%9A%E7%89%A9%E9%A6%86%E5%8F%8C%E5%B3%B0%E9%A6%86%E5%8C%BA%2C_2022-05-01_01.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0074-0c688e6bfa.jpg'
WHERE id = 74
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0075-a86a3552af.jpg'
WHERE id = 75
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0076-c9e643a9ed.jpg'
WHERE id = 76
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0077-888eaf9fda.png'
WHERE id = 77
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%9D%AD%E5%B7%9E%E5%A4%A9%E7%9B%AE%E9%87%8C%E5%B9%BF%E5%9C%BA.png';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 94
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E9%9B%81%E5%A1%94_%E5%A4%A7%E5%94%90%E4%B8%8D%E5%A4%9C%E5%9F%8E%E5%92%8C%E5%A4%A7%E9%9B%81%E5%A1%94.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0097-d14543e04b.jpg'
WHERE id = 97
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Giant_Wild_Goose_Pagoda.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0109-cafa963de9.jpg'
WHERE id = 109
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://p1-mp.oeeee.com/202503/20/1730x1280_67dbf4824c04b.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0110-ee1669cc41.jpg'
WHERE id = 110
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/a/ad/%E5%8D%97%E5%A4%B4%E5%8F%A4%E5%9F%8E%E5%8D%97%E9%97%A82022.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0115-be4f73e4b2.png'
WHERE id = 115
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://imgbdb4.bendibao.com/szbdb/tour/202210/14/20221014151703_33254.png';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0116-e1a62d0b9e.jpg'
WHERE id = 116
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://www.ourchinastory.com/images/content/shenzhen/2023/07/%E6%AD%A1%E6%A8%82%E6%B8%AF%E7%81%A31_x1.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0117-4fba56fd5f.jpg'
WHERE id = 117
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/04/Hongfa_Temple%2C_Shenzhen_001.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0118-9ff0f9b6c2.jpg'
WHERE id = 118
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://images.adsttc.com/media/images/583c/2371/e58e/ce78/6500/0090/large_jpg/P_0711_F009_DM.jpg?1480336224';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0119-70311c68a9.jpg'
WHERE id = 119
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://resource02.ulifestyle.com.hk/ulcms/content/article/image/w600/2024/01/20240117211416_073212e6190287e725454ae5d6064d4ca44f95ce.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0120-ef1288f8cd.jpg'
WHERE id = 120
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Ngtungsaan.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 134
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Hubei_Provincial_Museum.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 136
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/90/Nanjing_in_Ming_Dynasty.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0138-c56069e1f5.jpg'
WHERE id = 138
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Nanjing_Ming_Xiaoling_2017.11.11_08-10-27.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0166-29019439f9.jpg'
WHERE id = 166
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://r1.visitbeijing.com.cn/vbj-s/2023/0331/937c7ddf95f654f7c21b9959b5fc782b.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0167-3fc2c473b5.jpg'
WHERE id = 167
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/8/89/Dashala_Enterance_2010.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0168-6cf8fa0fea.jpg'
WHERE id = 168
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/99/Tian%27anmen_from_the_square_%2820200825114150%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0169-938079cd99.jpg'
WHERE id = 169
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/08/62684-Beijing-Tiananmen-Square_%2828609003992%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0175-dfdb5994ce.jpg'
WHERE id = 175
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/b/b6/China_National_Film_Museum_%2820240808162205%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0180-5cc85594c0.jpg'
WHERE id = 180
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://oss.gooood.cn/uploads/2015/07/008-Minsheng-Contemporary-Art-Museum-Beijing-China-by-Studio-Pei-Zhu-960x640.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0183-2af4843c6e.jpg'
WHERE id = 183
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E5%8C%97%E4%BA%AC%E8%A5%BF%E4%BB%80%E5%BA%93%E6%95%99%E5%A0%82%E5%A4%96%E9%83%A82023.3_%281%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0192-d62879ae27.jpg'
WHERE id = 192
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/09/Gate_of_Yeya_Lake_National_Wetland_Park_%2820160709114929%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0196-e9b790970e.jpg'
WHERE id = 196
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/c/c4/GreatWall_Badaling.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0197-657717e15b.jpg'
WHERE id = 197
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Juyongguanfromnorth.jpg';
