-- Replace remaining remote blind-box cover images with local fallback assets.
-- Generated by apps/api/scripts/fallbackBlindBoxCoverImages.ts.

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 20
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/6/64/%E5%9B%AD%E6%9E%97%E5%8D%9A%E7%89%A9%E9%A6%86.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 23
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/e/e5/A_picture_from_China_every_day_101.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 33
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/4/42/Colombia_Club_01.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 34
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/90/Shanghai_Tianzifang_%E4%B8%8A%E6%B5%B7%E7%94%B0%E5%AD%90%E5%9D%8A_-_panoramio.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 35
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/3/3e/%E4%B8%8A%E6%B5%B7%E5%89%8D%E6%BB%A9%E5%A4%AA%E5%8F%A4%E9%87%8C.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 36
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/d/db/1933%C2%B7%E4%B8%8A%E6%B5%B7%E5%85%AC%E5%85%B1%E7%A7%9F%E7%95%8C%E5%B7%A5%E9%83%A8%E5%B1%80%E5%AE%B0%E7%89%B2%E5%9C%BA%C2%B7%E4%B8%8A%E6%B5%B7%E8%99%B9%E5%8F%A3%C2%B7%EF%BC%88%E6%AD%A3%E9%9D%A2%E4%BF%AF%E6%8B%8D%EF%BC%89.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 37
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%88%90%E9%83%BD%E4%BA%BA%E6%B0%91%E5%85%AC%E5%9B%AD%E5%8C%97%E5%A4%A7%E9%97%A8.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 38
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_travel_045_%2836150300546%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 39
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Name_Wall_of_Dongjiao_Memory_Station%2C_Chengdu_Metro_Line_8.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 40
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_travel_045_%2836150300546%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 41
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Wangjianglou-Tower.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 42
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Du_Fu_cao_tang.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 43
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%B5%A3%E8%8A%B1%E6%BA%AA%E5%85%AC%E5%9B%AD%EF%BC%8D%E5%B0%8F%E6%A1%A5_-_panoramio.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 44
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_travel_045_%2836150300546%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 45
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Pengzhen_Street_Scene_1.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 47
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Jinli_Street_35201-Chengdu_%2849068150581%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 48
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%88%90%E9%83%BD%E5%8D%9A%E7%89%A9%E9%A6%86%E6%AD%A3%E9%97%A8.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 49
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E9%90%B5%E5%83%8F%E5%AF%BA%E5%B1%B1%E9%96%80.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0046-4c0346a5d2.jpg'
WHERE id = 50
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_travel_045_%2836150300546%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0051-02e15c4423.jpg'
WHERE id = 52
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Yongqingfang.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0051-02e15c4423.jpg'
WHERE id = 60
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/8/84/Canton_Tower_2013.11.15_18-12-45.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0051-02e15c4423.jpg'
WHERE id = 61
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/5/5b/53334088348_Guangdong_Museum_%28cropped%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0051-02e15c4423.jpg'
WHERE id = 63
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/5/54/Yuexiu_Park_Main_Gate_20260518.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0065-2f2ab5b481.jpg'
WHERE id = 72
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake%2C_Hangzhou_2025.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0065-2f2ab5b481.jpg'
WHERE id = 78
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%9D%AD%E5%B7%9E._%E5%A4%B4%E5%A4%A9%E7%AB%BA%EF%BC%88%E6%B3%95%E5%96%9C%E8%AE%B2%E5%AF%BA%EF%BC%89_-_panoramio.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 79
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 80
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E5%B1%B1%E5%9F%8E%E5%B7%B7%E4%B8%8A%E5%8C%BA.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 81
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 82
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%9D%8E%E5%AD%90%E5%9D%9D%E7%AB%99%E8%BD%BB%E8%BD%A8%E7%A9%BF%E6%A5%BC_0023.png';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 83
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E5%8D%97%E6%BF%B1%E8%B7%AF%E9%90%98%E6%A8%93.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 84
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 85
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E9%87%8D%E5%BA%86%E7%A3%81%E5%99%A8%E5%8F%A3%E5%8F%A4%E9%95%87%E8%BF%9C%E7%9C%BA.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 86
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 87
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E9%87%8D%E5%BA%86_%E9%95%BF%E6%B1%9F%E4%B8%8A%E7%9A%84%E6%B8%A1%E6%B1%9F%E7%B4%A2%E9%81%931_-_panoramio.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 88
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 89
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 90
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E9%87%8D%E5%BA%86_%E9%95%BF%E6%B1%9F%E4%B8%8A%E7%9A%84%E6%B8%A1%E6%B1%9F%E7%B4%A2%E9%81%932.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 91
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Chongqing_Zhongguo_Sanxia_Bowuguan_2014.04.21_11-11-06.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0024-d8cf76c15a.jpg'
WHERE id = 92
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 93
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 95
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Bei_Yuan_Men.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 96
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Shan3xi_History_Museum.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 98
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 99
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 100
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E7%A7%A6%E5%A7%8B%E7%9A%87%E5%B8%9D%E9%99%B5%C2%B7%E7%A7%A6%E5%A7%8B%E7%9A%87%E9%99%B5%C2%B7%E8%A5%BF%E5%AE%89%E8%87%A8%E6%BD%BC%C2%B7%EF%BC%88%E5%B0%81%E5%9C%9F%E6%AD%A3%E5%8C%97%E5%81%B4%EF%BC%89.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 101
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Baoqing_Temple_Pagoda.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 102
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 103
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Xi%27an_Museum_2024.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 104
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E6%9B%B2%E6%B1%9F%E6%B1%A0%E5%85%AC%E5%9B%AD%E8%88%AA%E6%8B%8D%E5%9B%BE.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 105
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0094-67d6b5b67b.jpg'
WHERE id = 106
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0109-cafa963de9.jpg'
WHERE id = 107
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Shenzhen%20Bay%20Park%20-%202019-12-09%20-%201.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0109-cafa963de9.jpg'
WHERE id = 108
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/8/85/Shenzhen_Lianhuashan_Park_South_East.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0109-cafa963de9.jpg'
WHERE id = 111
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/d/d4/%E5%8D%8E%E4%BE%A8%E5%9F%8E%E5%88%9B%E6%84%8F%E5%9B%AD.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0109-cafa963de9.jpg'
WHERE id = 112
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/98/Dafen_Oil_Painting_Village_%28Day%29.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0109-cafa963de9.jpg'
WHERE id = 113
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Gankeng_at_night%2C_December_2024_-9.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0109-cafa963de9.jpg'
WHERE id = 114
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/2/2d/%E6%B5%B7%E4%B8%8A%E4%B8%96%E7%95%8C%E6%98%8E%E5%8D%8E%E8%BD%AE.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 121
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/CN_-_Hubei_-_Wuhan_-_Kranichpagode.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 122
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/East_Lake_Wuhan.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 123
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/LiHuangPi_Road%EF%BC%8CWuhan%EF%BC%8CChina.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 124
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Tanhualin.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 125
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/East_Lake_Wuhan.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 126
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/East_Lake_Wuhan.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 127
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/East_Lake_Wuhan.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 128
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Hankou-Hanjiang-Lu-0247.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 129
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E5%8F%A4%E5%BE%B7%E5%AF%BA%E5%9C%86%E9%80%9A%E6%AE%BF2023.4_%281%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 130
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E5%92%B8%E5%AE%89%E5%9D%8A.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 131
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Wuhanam.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 132
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/East_Lake_Wuhan.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0134-ebdc03046b.jpg'
WHERE id = 133
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/d/d6/WuhanChuRiverHanStreet.png';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 135
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/91/Qinhuai_River_along_Fuzimiao_2008.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 137
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Hall_of_Sun_Yat-sen_Mausoleum.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 139
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Ninghai_Road.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 140
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Hall_of_Sun_Yat-sen_Mausoleum.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 141
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Xuanwuhu.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 142
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/91/Qinhuai_River_along_Fuzimiao_2008.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 143
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Banner_of_Nanjing_Museum%2C_2015-06-20.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 144
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/91/Qinhuai_River_along_Fuzimiao_2008.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 145
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/91/Qinhuai_River_along_Fuzimiao_2008.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 146
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Facade_of_Libraire_Avant-Garde%28Wutai_Mountain_branch%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 147
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Ginling_Machinery_Manufacture_Bureau_2011-03.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0136-45555a7d05.jpg'
WHERE id = 148
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Jiming_Temple_Nanjing%2C_2019_%28cropped%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 149
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Temple_of_Heaven_20160323_01.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 150
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/3/32/Beihai_Park_65414.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 151
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/7/7f/China_IMG_0502_%2829203705461%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 152
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/2/26/%E9%99%B6%E7%84%B6%E4%BA%AD_-_Joyful_Pavilion_-_2011.11_-_panoramio_%281%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 153
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/02/Yuyuantan_Park_2010.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 154
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/South_gate_of_Chaoyang_Park_20240818154413.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 155
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/4/49/Rockery_%26_Bamboo_in_Zizhuyuan.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 156
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Xishan_Qingxue_monument_at_Fragrant_Hills.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 157
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Beijing%20Botanical%20Garden%20-%20Oct%2009%20-%20IMG%201193.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 158
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Gate_of_Beijing_Zoo_%2820210219172711%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 159
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Lascar_Lama_temple_%284478042700%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 160
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Guozijian%20building%201.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 161
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Beijing_drum_tower.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 162
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Beijingbelltower1.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 163
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/d/d5/CN-pek-hutong-bei-trommelturm.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 164
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/7/73/View_down_Nanluoguxiang_2011.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 165
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Peking_Corner_of_the_Embassys_1910s.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 170
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/01/NationalGrandTheaterBeijing.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 171
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/3/36/Capital_Museum_in_Beijing.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 172
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/0/01/Beijing_Museum_of_Natural_History_exterior_2010_Sep_04.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 173
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Beijing_Planetarium_%2820221112164636%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 174
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/e/ee/China_Science_and_Technology_Museum_%2820210403155720%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 176
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Beijing_Automobile_Museum_%28from_north%29_2016_April.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 177
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Gate_of_China_Railway_Museum%2C_Dongjiao_%2820240808161123%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 178
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Ullens%20Center%20for%20Contemporary%20Art%20%28UCCA%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 179
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/SZ%20Art%20Center.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 181
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Whitepagoda%20temple.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 182
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Fa%20yuan%20temple02.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 184
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/7/78/Yangmeizhu_Xiejie_%2820240210151543%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 185
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/d/db/%E9%B2%81%E8%BF%85%E5%8D%9A%E7%89%A9%E9%A6%86_-_2162549628.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 186
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Main_gate%2C_Daguanyuan.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 187
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/98/%E5%8D%97%E6%B5%B7%E5%AD%90%E5%85%AC%E5%9B%AD.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 188
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/d/d9/West_gate_of_Grand_Canal_Forest_Park_%2820220415142954%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 189
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Central_Green_%2820220415132657%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 190
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Near_the_top_of_Baiwangshan_%2820160219151434%29.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 191
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://r1.visitbeijing.com.cn/vbj-s/2015/1208/20151208044934408.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 193
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Tanzhe_Si.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 194
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Jietai_Temple_%2820150117134744%29.JPG';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 195
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Great_Wall_of_China%2C_Mutianyu%2C_Huairou_County%2C_China-10June2009.jpg';

UPDATE activities
SET cover_image = '/uploads/activity-covers/blind-box/0009-885978e4c8.jpg'
WHERE id = 198
  AND description LIKE '来自《出行盲盒地点库%'
  AND cover_image = 'https://upload.wikimedia.org/wikipedia/commons/4/44/Happy_Valley_Beijing_%285%29.jpg';
