import { LegalDocumentScreen, type LegalBlock } from '@/components/legal-document-screen';

const PRIVACY_POLICY_BLOCKS: LegalBlock[] = [
  { type: 'paragraph', text: '生效日期：2026年7月2日' },
  { type: 'paragraph', text: '本政策说明我们如何收集、使用与保护用户信息。' },
  { type: 'heading', text: '1. 信息收集' },
  { type: 'item', text: '注册信息' },
  { type: 'item', text: '设备信息' },
  { type: 'item', text: '使用日志' },
  { type: 'item', text: 'AI输入内容' },
  { type: 'item', text: '第三方登录信息' },
  { type: 'heading', text: '2. AI数据使用' },
  { type: 'subheading', text: '2.1 使用范围' },
  { type: 'paragraph', text: '用于生成结果与系统优化。' },
  { type: 'subheading', text: '2.2 训练说明' },
  { type: 'paragraph', text: '仅使用匿名化数据，不包含个人敏感信息。' },
  { type: 'subheading', text: '2.3 用户选择' },
  { type: 'paragraph', text: '用户可关闭数据用于模型优化。' },
  { type: 'heading', text: '3. 信息使用目的' },
  { type: 'item', text: '提供服务' },
  { type: 'item', text: '优化产品' },
  { type: 'item', text: '安全风控' },
  { type: 'item', text: '合规要求' },
  { type: 'heading', text: '4. 信息共享' },
  { type: 'paragraph', text: '仅在以下情况共享：' },
  { type: 'item', text: '用户授权' },
  { type: 'item', text: '服务供应商' },
  { type: 'item', text: '法律要求' },
  { type: 'item', text: '安全保护' },
  { type: 'heading', text: '5. 支付信息' },
  { type: 'paragraph', text: '由第三方支付平台处理，不存储完整支付信息。' },
  { type: 'heading', text: '6. 订阅信息' },
  { type: 'paragraph', text: '包括订阅状态、账单与交易记录。' },
  { type: 'heading', text: '7. 数据安全' },
  { type: 'paragraph', text: '采用行业标准保护措施，但不保证绝对安全。' },
  { type: 'heading', text: '8. 用户权利' },
  { type: 'item', text: '访问数据' },
  { type: 'item', text: '修改数据' },
  { type: 'item', text: '删除账号' },
  { type: 'item', text: '关闭AI训练使用' },
  { type: 'heading', text: '9. Cookie' },
  { type: 'paragraph', text: '用于登录与分析优化。' },
  { type: 'heading', text: '10. 未成年人保护' },
  { type: 'paragraph', text: '需监护人同意使用。' },
  { type: 'heading', text: '11. 政策更新' },
  { type: 'paragraph', text: '可能随时更新并公告。' },
  { type: 'heading', text: '12. 联系方式' },
  { type: 'paragraph', text: 'support@example.com' },
];

export default function PrivacyPolicyScreen() {
  return <LegalDocumentScreen blocks={PRIVACY_POLICY_BLOCKS} title="隐私政策" />;
}
