import { LegalDocumentScreen, type LegalBlock } from '@/components/legal-document-screen';

const USER_AGREEMENT_BLOCKS: LegalBlock[] = [
  { type: 'paragraph', text: '生效日期：2026年7月2日' },
  { type: 'paragraph', text: '本协议适用于本产品/服务。您使用本服务即表示同意以下全部条款。' },
  { type: 'heading', text: '1. 定义' },
  { type: 'paragraph', text: '1. 用户：使用本服务的个人或组织' },
  { type: 'paragraph', text: '2. 本服务：由本公司提供的产品与功能' },
  { type: 'paragraph', text: '3. AI服务：基于人工智能模型提供的生成与处理能力' },
  { type: 'paragraph', text: '4. 订阅服务：需付费使用的功能' },
  { type: 'heading', text: '2. 服务内容' },
  { type: 'paragraph', text: '1. 提供AI生成、信息处理及工具服务' },
  { type: 'paragraph', text: '2. 可随时调整、更新或终止服务' },
  { type: 'paragraph', text: '3. 部分功能为付费服务' },
  { type: 'heading', text: '3. 账号规则' },
  { type: 'paragraph', text: '1. 用户需提供真实信息' },
  { type: 'paragraph', text: '2. 用户对账号行为负责' },
  { type: 'paragraph', text: '3. 禁止转让、出租或共享账号' },
  { type: 'heading', text: '4. 用户行为规范' },
  { type: 'paragraph', text: '不得：' },
  { type: 'item', text: '违法行为' },
  { type: 'item', text: '侵权行为' },
  { type: 'item', text: '恶意攻击系统' },
  { type: 'item', text: '传播病毒或垃圾信息' },
  { type: 'item', text: '破坏系统运行' },
  { type: 'heading', text: '5. AI服务特别条款' },
  { type: 'subheading', text: '5.1 AI输出性质' },
  { type: 'paragraph', text: 'AI生成内容仅供参考，不构成专业建议或承诺。' },
  { type: 'subheading', text: '5.2 免责说明' },
  { type: 'paragraph', text: '不保证AI输出的准确性、完整性或可靠性。' },
  { type: 'subheading', text: '5.3 使用限制' },
  { type: 'paragraph', text: '禁止用于：' },
  { type: 'item', text: '违法内容生成' },
  { type: 'item', text: '欺诈或误导行为' },
  { type: 'item', text: '深度伪造' },
  { type: 'item', text: '高风险决策场景' },
  { type: 'heading', text: '6. AI数据说明' },
  { type: 'paragraph', text: '用户输入可能用于匿名化优化模型，不包含可识别个人信息。' },
  { type: 'heading', text: '7. 支付与订阅' },
  { type: 'subheading', text: '7.1 付费服务' },
  { type: 'paragraph', text: '部分功能需付费使用。' },
  { type: 'subheading', text: '7.2 自动续费' },
  { type: 'paragraph', text: '用户同意可自动扣费，可随时关闭。' },
  { type: 'subheading', text: '7.3 退款规则' },
  { type: 'paragraph', text: '原则不退款，重复扣费或系统问题可申请处理。' },
  { type: 'heading', text: '8. 知识产权' },
  { type: 'paragraph', text: '所有内容归本公司所有，禁止未经授权使用。' },
  { type: 'heading', text: '9. 免责声明' },
  { type: 'paragraph', text: '因AI输出导致的后果由用户自行承担。' },
  { type: 'heading', text: '10. 法律适用' },
  { type: 'paragraph', text: '适用所在地法律。' },
  { type: 'heading', text: '11. 联系方式' },
  { type: 'paragraph', text: 'support@example.com' },
];

export default function UserAgreementScreen() {
  return <LegalDocumentScreen blocks={USER_AGREEMENT_BLOCKS} title="用户协议" />;
}
