import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import mysql from "mysql2/promise";

import { config } from "../src/config.js";

type CoverRow = {
  id: number;
  city_id: number;
  city_name: string;
  title: string;
  cover_image: string;
};

type Replacement = {
  id: number;
  title: string;
  sourceUrl: string;
  localPath: string;
};

const migrationPath = resolve(
  process.cwd(),
  "..",
  "..",
  "database",
  "migrations",
  "023_fallback_remaining_blind_box_cover_images.sql",
);

function sqlString(value: string) {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
}

function buildMigration(replacements: Replacement[]) {
  return [
    "-- Replace remaining remote blind-box cover images with local fallback assets.",
    "-- Generated by apps/api/scripts/fallbackBlindBoxCoverImages.ts.",
    "",
    ...replacements.flatMap((item) => [
      `UPDATE activities`,
      `SET cover_image = ${sqlString(item.localPath)}`,
      `WHERE id = ${item.id}`,
      `  AND description LIKE '来自《出行盲盒地点库%'`,
      `  AND cover_image = ${sqlString(item.sourceUrl)};`,
      "",
    ]),
  ].join("\n");
}

const connection = await mysql.createConnection(config.database);

try {
  const [localRows] = await connection.execute(
    `SELECT a.id, a.city_id, c.name AS city_name, a.title, a.cover_image
     FROM activities a
     INNER JOIN cities c ON c.id = a.city_id
     WHERE a.description LIKE '来自《出行盲盒地点库%'
       AND a.cover_image LIKE '/uploads/%'
     ORDER BY a.city_id ASC, a.id ASC`,
  );
  const localCovers = localRows as CoverRow[];

  if (localCovers.length === 0) {
    throw new Error("没有可用的本地盲盒封面，无法兜底替换。");
  }

  const localByCity = new Map<number, string>();
  for (const row of localCovers) {
    if (!localByCity.has(row.city_id)) {
      localByCity.set(row.city_id, row.cover_image);
    }
  }
  const globalFallback = localCovers[0]!.cover_image;

  const [remoteRows] = await connection.execute(
    `SELECT a.id, a.city_id, c.name AS city_name, a.title, a.cover_image
     FROM activities a
     INNER JOIN cities c ON c.id = a.city_id
     WHERE a.description LIKE '来自《出行盲盒地点库%'
       AND a.cover_image REGEXP '^https?://'
     ORDER BY a.id ASC`,
  );
  const remoteCovers = remoteRows as CoverRow[];

  if (remoteCovers.length === 0) {
    console.log("没有剩余远程盲盒封面需要兜底。");
    process.exit(0);
  }

  const replacements: Replacement[] = remoteCovers.map((row) => ({
    id: row.id,
    title: row.title,
    sourceUrl: row.cover_image,
    localPath: localByCity.get(row.city_id) ?? globalFallback,
  }));

  for (const item of replacements) {
    await connection.execute(
      `UPDATE activities
       SET cover_image = ?
       WHERE id = ?
         AND description LIKE '来自《出行盲盒地点库%'
         AND cover_image = ?`,
      [item.localPath, item.id, item.sourceUrl],
    );
  }

  await writeFile(migrationPath, buildMigration(replacements), "utf8");
  console.log(`剩余盲盒封面兜底完成：${replacements.length} 张`);
  console.log(`迁移文件：${migrationPath}`);
} finally {
  await connection.end();
}
